#!/bin/bash

echo "🎨 New Anthropic-Inspired Design Ready for Deployment!"
echo "===================================================="
echo ""
echo "Your website has been completely redesigned with:"
echo ""
echo "✅ Pure black background (#000000)"
echo "✅ Teal accent color (#14B8A6)"
echo "✅ Minimal, clean typography"
echo "✅ Professional layout inspired by Anthropic.com"
echo "✅ Smooth animations and glassmorphism effects"
echo "✅ Case studies with impressive metrics"
echo "✅ No emoji clutter - clean geometric shapes only"
echo ""
echo "📁 Files ready for upload:"
echo "------------------------"
ls -la index.html styles.css main.js _redirects _headers *.html 2>/dev/null | grep -E "(index|styles|main|_redirects|_headers|\.html)" | awk '{print "   ✓", $9}'
echo ""
echo "🚀 To deploy your new design:"
echo "----------------------------"
echo "1. Open: https://dash.cloudflare.com"
echo "2. Go to: Workers & Pages → santiago-sainz-ai"
echo "3. Click: 'Create deployment'"
echo "4. Choose: 'Upload assets'"
echo "5. Select ALL files listed above"
echo "6. Click: 'Deploy'"
echo ""
echo "⏱️  Deployment takes ~30 seconds"
echo ""
echo "🌐 Your sleek new website will be live at:"
echo "   • https://www.santiagosainz.com"
echo "   • https://santiagosainz.com"
echo "   • https://santiago-sainz-ai.pages.dev"
echo ""
echo "💡 Pro tip: Clear your browser cache after deployment!"